// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get Supabase URL from env or construct from project ID
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 
  (import.meta.env.VITE_SUPABASE_PROJECT_ID 
    ? `https://${import.meta.env.VITE_SUPABASE_PROJECT_ID}.supabase.co`
    : 'https://eqphojnrsoxksyaqdswi.supabase.co'); // Fallback to actual project ID

// Get Supabase anon key from env
// If not set, use fallback (for development/testing only - should be set via env in production)
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  'sb_publishable_p93iwBXX_GJ3R77bPq9LJQ_ahJJi_7J'; // Fallback for development

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export Supabase URL for use in API calls
export { SUPABASE_URL };